### ISSUE TITLE
Issue with cleanup_oldreleases

### ISSUE THREAD

**Issue by robertvrabel** [nickfan/envoy-deployscript#1]
This line: https://github.com/nickfan/envoy-deployscript/blob/master/Envoy.blade.php#L511

```
ls -dt {{ $release_dir }}/* | tail -n +4 | xargs -d '\n' rm -rf;
```

For my case that command basically started traversing through my whole server trying to delete everything. Tried to debug it the best I could but couldn't pin point it exactly. Its like the last command doesn't return the paths properly. I'd be happy to debug more if anyone has suggestions.
Server info is: Red Hat Enterprise Linux Server release 6.6 (Santiago) 

This command worked for my case as a replacement:

```
(ls -rd {{ $release_dir }}/*|head -n 4;ls -d {{ $release_dir }}/*)|sort|uniq -u|xargs rm -rf
```

**Comment by nickfan** [comment]
ok,i see, could you issue a pull request?

**Comment by robertvrabel** [comment]
@nickfan Just submitted it: https://github.com/nickfan/envoy-deployscript/pull/3
