### ISSUE TITLE
 envoy-deployscript脱离于项目独立部署

### ISSUE THREAD

**Issue by ayamzh** [nickfan/envoy-deployscript#15]
可不可以增加个 支持多个项目的功能。比如 app A和B，每个app又有TEST PROD等多个环境。用一个DEPLOYSCRIPT项目管理AB 两个项目的发布

**Comment by nickfan** [comment]
每个项目直接加入deployscript文件即可，每个环境单独写配置文件，然后软链指向目标环境配置。
![image](https://user-images.githubusercontent.com/100613/63250538-73818480-c29e-11e9-8d53-fbf518d8461e.png)

**Comment by ayamzh** [comment]
这个我理解 我意思是，能不能把envoy独立作为一个发布服务器，在他里面维护多个项目，这样运维只用关注这一个项目来做发布操作了 而不需要每个项目里在维护一套ENVOY




------------------ 原始邮件 ------------------
发件人: "nick"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午4:29
收件人: "nickfan/envoy-deployscript"<envoy-deployscript@noreply.github.com>;
抄送: "香吉士 "<75872332@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nickfan/envoy-deployscript]  envoy-deployscript脱离于项目独立部署 (#15)




每个项目直接加入deployscript文件即可，每个环境单独写配置文件，然后软链指向目标环境配置。

**Comment by nickfan** [comment]
嗯，挺好的想法，不过，envoy的脚本还是受限制比较多的，流程比较死，自定义有限，所以有不少业务定制功能还是需要直接修改envoy部署脚本的源码的，后续暂时没有改进计划，9102年了，用docker/k8s写shell配置文件吧，本质还是一样的。

**Comment by ayamzh** [comment]
了解，感谢分享。




------------------ 原始邮件 ------------------
发件人: "nick"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 下午4:35
收件人: "nickfan/envoy-deployscript"<envoy-deployscript@noreply.github.com>;
抄送: "香吉士 "<75872332@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [nickfan/envoy-deployscript]  envoy-deployscript脱离于项目独立部署 (#15)




嗯，挺好的想法，不过，envoy的脚本还是受限制比较多的，流程比较死，自定义有限，所以有不少业务定制功能还是需要直接修改envoy部署脚本的源码的，后续暂时没有改进计划，9102年了，用docker/k8s写shell配置文件吧，本质还是一样的。
