### ISSUE TITLE
Use `php artisan config:clear`

### ISSUE THREAD

**Issue by blakemckeeby** [nickfan/envoy-deployscript#4]
Hey Nick,

Thanks for sharing this. It is very well done! 

I noticed one problem when using. I enabled all of the optimize options (optimize, config_cache, route_cache) in the envoy.config.php file. 

I noticed for some reason that when the Illuminate View module was trying to generate cached views it was having permissions issues because it was attempting to write to the storage directory in the _source_ instead of the current directory.

ErrorException: file_put_contents(/usr/share/nginx/html/telco/source/storage/framework/views/9a739dce5a8556c025010f5ff737d04df7214471.php): failed to open stream: Permission denied in /usr/share/nginx/html/telco/releases/release_20160427145447/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81

After about 30 minutes of digging, it seems that the directory that View module writes to for caching is controlled by the view.compiled config option. Since the configs had been cached (i.e. compiled in app/shared/bootstrap/cache/config.php) the value had gotten set incorrectly in this file. Running `php artisan config:clear` solved. 

Proposing changing line ~132 of envoy.config.php to 

 'config_cache'=>'php artisan config:clear && php artisan config:cache',

**Comment by blakemckeeby** [comment]
Hey Nick,

I was a little bit off on my last update.. 

While running `artisan config:clear` in the current directory on the remote host solves the problem after the code has been deployed solves the problem.. changing the `runtime_optimize_command` does not solve the problem. 

The problem is that the  `runtime_optimize_command` is being performed within the $source_dir instead of the current directory. 

Starting at line 986. 
@task('runtimeoptimize_remotesrc',['on' => $server_labels, 'parallel' => true])
    echo "RemoteSource Runtime optimize...";
    cd {{ $source_dir }};

**Comment by blakemckeeby** [comment]
And to add the final update to this saga (sorry for the run around).

Turns out the issue is the issue is the optimize command `php artisan optimize`. When this command is run and APP_DEBUG=false, the source/bootstrap/cache/compiled.php is created and then copied to the shared directory, resulting in the problem. 

Short term fix is to turn off `optimize` in envoy.config.php but long term fix would be change   so that `runtimeoptimize_remotesrc` task (which is run as the last task of `pack_remotepack`) executes after `syncreleasetoapp_version` so that `php artisan optimize` can be executed within the `current` directory instead of the source directory.

**Comment by nickfan** [comment]
@blakemckeeby thx 4 yr feedback,
could u write a pull request 4 this?

**Comment by blakemckeeby** [comment]
@nickfan I honestly don't understand the entire script so I can't be completely confident that I wont introduce an issue, but I'm pretty sure this can be resolved by just changing the order of sub processes in the `deploy` task and the target of the `cd` operation in the `runtimeoptimize_remotesrc` task. 

I will give it a whirl and submit PR.

**Comment by nickfan** [comment]
ok,i got you, i changed deploy strategy, only run runtime optimize on appdir (add runtimeoptimize_version task) and updated the code,thanks for your reply again.
if you have use envoy-deployscript on your prev release, you should do 
`php artisan clear-compiled && php artisan config:clear && php artisan route:clear` on your local source dir or your remote source dir
