### ISSUE TITLE
Shared sub-directory permissions

### ISSUE THREAD

**Issue by richiepearce** [nickfan/envoy-deployscript#6]
Hey,  

Thanks for sharing your envoy script, it's greatly helped me out.

I may have misunderstood but I need the **storage** and **bootstrap/cache** directories to have the **www-data** user.  I've set the service_owner_default to www-data but it doesn't change.

The 'syncshareddata_remotesrc' task looks like it should be changing the group, but it doesn't work.

**Comment by nickfan** [comment]
what's the login user in your config file?
the 'syncshareddata_remotesrc' task will use {$tmpdir}/service_owner file content (which is your server connection login user,scp to remote server on 'rcp_env_to_remote' task )

the 'service_owner_default' settings will work only when the script can't find a login user on your server connection string config settings.

**Comment by richiepearce** [comment]
I see.  The login user is a deploy user which is fine for most of the files and directories.  I need to 'chown' the shared directories somewhere in the deployment to get them owned by www-data.

EDIT - It could be a problem with my setup.  I changed all the **chgrp** commands to **sudo chgrp** and it changes to group to www-data as expected.

**Comment by nickfan** [comment]
ok,if you need to set shared directories owner different from login user you can custom the script section 'syncshareddata_remotesrc' code:

```
if [ -e {{ $tmp_dir }}/service_owner ]; then
        service_owner=`cat {{ $tmp_dir }}/service_owner`;
    else
        service_owner="{{ $settings['service_owner_default'] }}";
    fi
```

into

```

service_owner="{{ $settings['service_owner_default'] }}";

```

and set 

```
$settings['service_owner_default'] = 'www-data';
```

in your config file.

**Comment by richiepearce** [comment]
Thank you for your help.

**Comment by newtek-bneff** [comment]
I have the same issue and I made the change mentioned above and now I get an error:
```
$ rsync: chgrp "/var/www/{app_name}/shared/storage/." failed: Operation not permitted (1)
$ rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```
