### ISSUE TITLE
Composer update process

### ISSUE THREAD

**Issue by enstain** [nickfan/envoy-deployscript#9]
When I run "envoy run deploy" for the first time, "composer install" command is executed and composer installs all my required packages correctly. But when I continue development process and add some new dependencies into composer.json, "envoy run deploy" still executes "composer install" instead of "composer update" and new packages aren't installed. 

So, I have to manually change $settings['deps_install_command']['composer'] value to "composer update ....". Then I have correct deployment process.

**Comment by basavind** [comment]
Deploy process shouldn't use composer update. Check that you haven't ignored composer.lock file in repository.

**Comment by enstain** [comment]
@basavind You're right, including composer.lock to the repo did the trick
